/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/input` | `/input`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/result` | `/result`; params?: Router.UnknownInputParams; } | { pathname: `${'/(web)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(web)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(web)'}/drawing` | `/drawing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(web)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/input` | `/input`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/result` | `/result`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(web)'}/auth` | `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(web)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(web)'}/drawing` | `/drawing`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(web)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/input${`?${string}` | `#${string}` | ''}` | `/input${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/result${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `${'/(web)'}/auth${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `${'/(web)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(web)'}/drawing${`?${string}` | `#${string}` | ''}` | `/drawing${`?${string}` | `#${string}` | ''}` | `${'/(web)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/input` | `/input`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/result` | `/result`; params?: Router.UnknownInputParams; } | { pathname: `${'/(web)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(web)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(web)'}/drawing` | `/drawing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(web)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
